# Generated by Django 5.0.6 on 2026-05-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(help_text='Business name or handle reported', max_length=255)),
                ('report_type', models.CharField(choices=[('Non-delivery', 'Non-delivery'), ('Fake Products', 'Fake Products'), ('Payment Fraud', 'Payment Fraud'), ('Identity Theft', 'Identity Theft'), ('Investment Scam', 'Investment Scam'), ('Phishing', 'Phishing'), ('Impersonation', 'Impersonation'), ('Other', 'Other')], default='Other', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('amount_lost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('evidence_url', models.URLField(blank=True)),
                ('reporter_email', models.EmailField(blank=True, help_text='Optional – for follow-up only', max_length=254)),
                ('is_public', models.BooleanField(default=True, help_text='Show anonymised on public feed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScamAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alert_type', models.CharField(choices=[('Investment Scam', 'Investment Scam'), ('Online Shopping', 'Online Shopping'), ('Job Scam', 'Job Scam'), ('Romance Scam', 'Romance Scam'), ('Crypto Fraud', 'Crypto Fraud'), ('M-Pesa Fraud', 'M-Pesa Fraud'), ('Phishing', 'Phishing'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(help_text='@handle or domain', max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reg_number', models.CharField(blank=True, max_length=100)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=50)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('has_physical_address', models.BooleanField(default=False)),
                ('badge', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('at-risk', 'At Risk'), ('flagged', 'Flagged'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('verified_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='stamps.applicant')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
    ]
