# Generated by Django 5.0.6 on 2026-05-08 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_fraudreport_scamalert_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_handle', models.CharField(help_text='Unique @handle', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('retail', 'Retail'), ('food', 'Food & Beverage'), ('tech', 'Technology'), ('finance', 'Finance'), ('health', 'Health & Wellness'), ('logistics', 'Logistics'), ('other', 'Other')], default='other', max_length=50)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text='True when a digital stamp has been issued')),
                ('badge_status', models.CharField(default='unverified', max_length=20)),
                ('certificate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('stamp_approved', 'Stamp Approved'), ('stamp_renewal', 'Stamp Renewal Due'), ('new_report', 'New Fraud Report'), ('system', 'System Message')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stamps.businessprofile')),
            ],
            options={
                'verbose_name': 'Business Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileFraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Non-delivery', 'Non-delivery'), ('Fake Products', 'Fake Products'), ('Payment Fraud', 'Payment Fraud'), ('Identity Theft', 'Identity Theft'), ('Investment Scam', 'Investment Scam'), ('Phishing', 'Phishing'), ('Impersonation', 'Impersonation'), ('Other', 'Other')], default='Other', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reporter_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('severity_category', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('severity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reports', to='stamps.businessprofile')),
            ],
            options={
                'verbose_name': 'Profile Fraud Report',
                'ordering': ['-created_at'],
            },
        ),
    ]
